name: Build and Deploy
on:
  workflow_dispatch:
  push:
    branches:
       - main
  pull_request:
    branches:
       - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
  
  deploy:
    needs: ['test']
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: '1.17.0'
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: build go binary
        id: build
        run: |
          GOOS=linux GOARCH=amd64 go build -o btccron main.go
          echo "::set-output name=bin::btccron"

      - name: get IP address
        id: ip-prod
        run: echo "::set-output name=ip-address::$(aws ssm get-parameter --with-decryption --name "/prod/vm/ip" | jq -r .Parameter.Value)"
        shell: bash

      - name: ansible
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ops/ansible/playbook.yml
          key: ${{ secrets.SSH_PRIVATE_KEY_PROD }}
          options: |
            -i "${{ steps.ip-prod.outputs.ip-address }},"
            --extra-vars mongo=${{ secrets.MONGO_CONNECTION_STRING_PROD }}
            --extra-vars mongo_db=btc
            --extra-vars bin="../../${{ steps.build.outputs.bin }}"
            --verbose
  
  post-deploy:
    needs: ['deploy']
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2